USE [master]
GO
/****** Object:  Database [Ploomes]    Script Date: 24/01/2024 16:17:38 ******/
CREATE DATABASE [Ploomes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ploomes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Ploomes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ploomes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Ploomes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Ploomes] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ploomes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ploomes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ploomes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ploomes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ploomes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ploomes] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ploomes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ploomes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ploomes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ploomes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ploomes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ploomes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ploomes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ploomes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ploomes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ploomes] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ploomes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ploomes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ploomes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ploomes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ploomes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ploomes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ploomes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ploomes] SET RECOVERY FULL 
GO
ALTER DATABASE [Ploomes] SET  MULTI_USER 
GO
ALTER DATABASE [Ploomes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ploomes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ploomes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ploomes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ploomes] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Ploomes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Ploomes', N'ON'
GO
ALTER DATABASE [Ploomes] SET QUERY_STORE = ON
GO
ALTER DATABASE [Ploomes] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Ploomes]
GO
/****** Object:  User [admin]    Script Date: 24/01/2024 16:17:38 ******/
CREATE USER [admin] FOR LOGIN [admin] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 24/01/2024 16:17:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
	[UserId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 24/01/2024 16:17:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[Email] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Customer]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
USE [master]
GO
ALTER DATABASE [Ploomes] SET  READ_WRITE 
GO
